BEGIN TRANSACTION;
-- VEGETATION definition

CREATE TABLE "VEGETATION" (
	"VEGETATIONID"	TEXT,
	"PLOTID"	TEXT,
	"VSNSPECIESCODE"	TEXT,
	"SPECIMENNUMBER"	INTEGER,
	"QUAD1"	NUMERIC,
	"QUAD2"	NUMERIC,
	"QUAD3"	NUMERIC,
	"QUAD4"	NUMERIC,
	"ELCLAYER3"	NUMERIC,
	"ELCLAYER4"	NUMERIC,
	"ELCLAYER5"	NUMERIC,
	"ELCLAYER6"	NUMERIC,
	"ELCLAYER7"	NUMERIC,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"QUAD1_ELC4"	NUMERIC,
	"QUAD2_ELC4"	NUMERIC,
	"QUAD3_ELC4"	NUMERIC,
	"QUAD4_ELC4"	NUMERIC,
	"QUAD1_ELC5"	NUMERIC,
	"QUAD2_ELC5"	NUMERIC,
	"QUAD3_ELC5"	NUMERIC,
	"QUAD4_ELC5"	NUMERIC,
	"QUAD1_ELC6"	NUMERIC,
	"QUAD2_ELC6"	NUMERIC,
	"QUAD3_ELC6"	NUMERIC,
	"QUAD4_ELC6"	NUMERIC,
	"QUAD1_ELC7"	NUMERIC,
	"QUAD2_ELC7"	NUMERIC,
	"QUAD3_ELC7"	NUMERIC,
	"QUAD4_ELC7"	NUMERIC,
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("VEGETATIONID")
);

CREATE INDEX "VEGETATTIONID" ON "VEGETATION" (
	"VEGETATIONID"
);
CREATE INDEX "VEGDELETED" ON "VEGETATION" (
	"IsDeleted"
);

-- TREE definition

CREATE TABLE "TREE" (
	"TREEID"	TEXT,
	"PLOTID"	TEXT,
	"SECTION"	INTEGER,
	"TREENUMBER"	INTEGER,
	"SPECIESCODE"	INTEGER,
	"TAG_TYPE"	TEXT,
	"TREEORIGINCODE"	TEXT,
	"VSNSTATUSCODE"	TEXT,
	"TREESTATUSCODE"	TEXT,
	"VIGOURCODE"	INTEGER,
	"HEIGHTTODBH"	NUMERIC,
	"DBH"	NUMERIC,
	"HT"	NUMERIC,
	"LENGTH"	NUMERIC,
	"DBHIN"	TEXT,
	"CROWNIN"	TEXT,
	"LIVE_CROWN_RATIO"	INTEGER,
	"CROWNCLASSCODE"	TEXT,
	"CROWN_POSITION"	INTEGER,
	"CROWNDAMAGECODE"	INTEGER,
	"DEFOLIATING_INSECT"	INTEGER,
	"FOLIAR_DISEASE"	INTEGER,
	"STEMQUALITYCODE"	TEXT,
	"BARKRETENTIONCODE"	INTEGER,
	"WOODCONDITIONCODE"	INTEGER,
	"DECAYCLASS"	INTEGER,
	"MORTALITYCAUSECODE"	INTEGER,
	"BROKENTOP"	TEXT,
	"AZIMUTH"	NUMERIC,
	"DISTANCE"	NUMERIC,
	"CROWNWIDTH1"	NUMERIC,
	"CROWNWIDTH2"	NUMERIC,
	"DBH1"	NUMERIC,
	"DBH2"	NUMERIC,
	"DIRECTTOTALHEIGHT"	NUMERIC,
	"OCULARTOTALHEIGHT"	NUMERIC,
	"HEIGHTTODEADTIP"	NUMERIC,
	"DIRECTHEIGHTTOCONTLIVECROWN"	NUMERIC,
	"OCULARHEIGHTTOCONTLIVECROWN"	NUMERIC,
	"DIRECTOFFSETDISTANCE"	NUMERIC,
	"DEGREEOFLEAN"	INTEGER,
	"HEIGHTTOCORE"	NUMERIC,
	"CORESTATUSCODE"	TEXT,
	"SOUNDWOODLENGTH"	NUMERIC,
	"FIELDAGE"	INTEGER,
	"OFFICERINGCOUNT"	INTEGER,
	"MISSINGRINGS"	INTEGER,
	"COMMENTS"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"ERRORCOUNT"	INTEGER DEFAULT 0,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("TREEID")
);

CREATE INDEX "TREETREENUM" ON "TREE" (
	"PLOTID",
	"TREENUMBER"
);
CREATE INDEX "TREEID" ON "TREE" (
	"TREEID"
);
CREATE INDEX "TREEDELETED" ON "TREE" (
	"IsDeleted"
);

-- STEMMAP definition

CREATE TABLE "STEMMAP" (
	"STEMMAPID"	TEXT,
	"TREEID"	TEXT,
	"AZIMUTH"	INTEGER,
	"DISTANCE"	NUMERIC,
	"CROWNWIDTH1"	NUMERIC,
	"CROWNWIDTH2"	NUMERIC,
	"CROWNOFFSETAZIMUTH"	INTEGER,
	"CROWNOFFSETDISTANCE"	NUMERIC,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("STEMMAPID")
);

CREATE INDEX "STEMMAPID" ON "STEMMAP" (
	"STEMMAPID"
);
CREATE INDEX "STEMMAPDELETED" ON "STEMMAP" (
	"IsDeleted"
);

-- SOIL definition

CREATE TABLE "SOIL" (
	"SOILID"	TEXT,
	"PLOTID"	TEXT,
	"HORIZONNUMBER"	INTEGER,
	"DEPTHFROM"	NUMERIC,
	"DEPTHTO"	NUMERIC,
	"HORIZON"	TEXT,
	"DECOMPOSITIONCODE"	TEXT,
	"MINERALTEXTURECODE"	TEXT,
	"POREPATTERNCODE"	TEXT,
	"STRUCTURE"	TEXT,
	"MATRIXCOLOUR"	TEXT,
	"MOTTLECOLOUR"	TEXT,
	"PERCENTGRAVEL"	INTEGER,
	"PERCENTCOBBLE"	INTEGER,
	"PERCENTSTONE"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"GLEYCOLOUR"	TEXT,
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("SOILID")
);

CREATE INDEX "SOILPLOTHORIZON" ON "SOIL" (
	"PLOTID",
	"HORIZONNUMBER",
	"DEPTHFROM",
	"DEPTHTO"
);
CREATE INDEX "SOILID" ON "SOIL" (
	"SOILID"
);
CREATE INDEX "SOILDELETED" ON "SOIL" (
	"IsDeleted"
);

-- SMALLTREE definition

CREATE TABLE "SMALLTREE" (
	"SMALLTREEID"	TEXT,
	"PLOTID"	TEXT,
	"SPECIESCODE"	INTEGER,
	"HT_CLASS1_COUNT"	INTEGER,
	"HT_CLASS2_COUNT"	INTEGER,
	"HT_CLASS3_COUNT"	INTEGER,
	"HT_CLASS4_COUNT"	INTEGER,
	"HT_CLASS5_COUNT"	INTEGER,
	"HT_CLASS6_COUNT"	INTEGER,
	"HT_CLASS7_COUNT"	INTEGER,
	"HT_CLASS8_COUNT"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"HEIGHT"	NUMERIC,
	"COUNT"	INTEGER,
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("SMALLTREEID")
);

CREATE INDEX "SMALLTREEID" ON "SMALLTREE" (
	"SMALLTREEID"
);
CREATE INDEX "SMALLTREEDELETED" ON "SMALLTREE" (
	"IsDeleted"
);
-- PROJECT definition

CREATE TABLE "PROJECT" (
	"PROJECTID"	TEXT,
	"NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	"PROJECT_DATE"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("PROJECTID")
);

CREATE INDEX "PROJECTDELETED" ON "PROJECT" (
	"IsDeleted"
);

-- PLOT definition

CREATE TABLE "PLOT" (
	"PLOTID"	TEXT,
	"PROJECTID"	TEXT,
	"VSNPLOTTYPECODE"	TEXT,
	"VSNPLOTNAME"	TEXT,
	"PLOTKEY"	TEXT,
	"PLOTOVERVIEWDATE"	TEXT,
	"MEASURETYPECODE"	TEXT,
	"LEAD_SPP"	INTEGER,
	"GROWTHPLOTNUMBER"	INTEGER,
	"CROWN_CLOSURE"	INTEGER,
	"FIELD_CREW1"	TEXT,
	"FIELD_CREW2"	TEXT,
	"FIELD_CREW3"	TEXT,
	"FIELD_CREW4"	TEXT,
	"FIELD_CREW5"	TEXT,
	"FIELD_CREW6"	TEXT,
	"DECLINATION"	INTEGER,
	"UTMZONE"	INTEGER,
	"EASTING"	NUMERIC,
	"NORTHING"	NUMERIC,
	"DATUM"	TEXT,
	"PLOTOVERVIEWNOTE"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"SynchRequired"	TEXT,
	"NONSTANDARDTYPECODE"	INTEGER,
	"ACCESSCONDITIONCODE"	INTEGER,
	"MEASUREYEAR"	INTEGER,
	"EXISTINGPLOTNAME"	TEXT,
	"EXISTINGPLOTTYPECODE"	TEXT,
	"DISTANCETARGETMOVED"	NUMERIC,
	"AZIMUTHTARGETMOVED"	INTEGER,
	"MATURITYCLASSCODE1"	TEXT,
	"MATURITYCLASSRATIONALE1"	TEXT,
	"MATURITYCLASSCODE2"	TEXT,
	"MATURITYCLASSRATIONALE2"	TEXT,
	"CANOPYSTRUCTURECODE1"	TEXT,
	"CANOPYSTRUCTURECODE2"	TEXT,
	"MAINCANOPYORIGINCODE1"	INTEGER,
	"MAINCANOPYORIGINCODE2"	INTEGER,
	"DISTURBANCECODE1"	INTEGER,
	"DISTURBANCECODE2"	INTEGER,
	"SITERANK"	INTEGER,
	"CROWNDAMAGECODE"	INTEGER,
	"VIGOURCODE"	INTEGER,
	"DAMAGEDESCRIPTION"	TEXT,
	"FORESTHEALTHDATE"	TEXT,
	"FORESTHEALTHNOTE"	TEXT,
	"FORESTHEALTHPERSON"	TEXT,
	"FOLLOWUPREQUIRED"	TEXT,
	"SMALLTREESHRUBAREA"	INTEGER,
	"SMALLTREESHRUBDATE"	TEXT,
	"SMALLTREESHRUBNOTE"	TEXT,
	"SMALLTREEPERSON"	TEXT,
	"UNDERSTORYVEGETATIONDATE"	TEXT,
	"UNDERSTORYVEGETATIONAREA"	INTEGER,
	"UNDERSTORYVEGETATIONNOTE"	TEXT,
	"UNDERSTORYVEGETATIONPERSON"	TEXT,
	"UNDERSTORYCENSUSDATE"	TEXT,
	"UNDERSTORYCENSUSNOTE"	TEXT,
	"UNDERSTORYCENSUSPERSON"	TEXT,
	"DOWNWOODYDEBRISDATE"	TEXT,
	"DOWNWOODYDEBRISNOTE"	TEXT,
	"DOWNWOODYDEBRISPERSON"	TEXT,
	"LINELENGTH1"	NUMERIC,
	"LINELENGTH2"	NUMERIC,
	"DEFORMITYDATE"	TEXT,
	"DEFORMITYNOTE"	TEXT,
	"DEFORMITYPERSON"	TEXT,
	"STANDINFODATE"	TEXT,
	"STANDINFONOTE"	TEXT,
	"STANDINFOPERSON"	TEXT,
	"PERCENTAFFECTED"	INTEGER,
	"PERCENTMORTALITY"	INTEGER,
	"AGEPERSON"	TEXT,
	"AGEDATE"	TEXT,
	"AGENOTE"	TEXT,
	"STEMMAPPINGPERSON"	TEXT,
	"STEMMAPPINGDATE"	TEXT,
	"STEMMAPPINGNOTE"	TEXT,
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	"LastSynched"	TEXT,
	PRIMARY KEY("PLOTID")
);

CREATE INDEX "PLOTID" ON "PLOT" (
	"PLOTID"
);
CREATE INDEX "PLOTDELETED" ON "PLOT" (
	"IsDeleted"
);

-- ECOSITE definition

CREATE TABLE "ECOSITE" (
	"ECOSITEID"	TEXT,
	"PLOTID"	TEXT,
	"HUMUSFORMCODE"	INTEGER,
	"DRAINAGECLASSCODE"	INTEGER,
	"STRATIFIED"	TEXT,
	"EFFECTIVE_PORE_PATTERN"	TEXT,
	"ELC_SUBSTRATE_TYPE"	TEXT,
	"DEPTHTODISTINCTMOTTLES"	INTEGER,
	"DEPTHTOPROMINENTMOTTLES"	INTEGER,
	"DEPTHTOGLEY"	INTEGER,
	"DEPTHTOBEDROCK"	INTEGER,
	"DEPTHTOCARBONATES"	INTEGER,
	"MOISTURE_REGIME_DEPTH_CLASS"	TEXT,
	"MOISTUREREGIMECODE"	TEXT,
	"MODEOFDEPOSITIONCODE1"	TEXT,
	"MODEOFDEPOSITIONCODE2"	TEXT,
	"FUNCTIONALROOTINGDEPTH"	INTEGER,
	"MAXIMUMROOTINGDEPTH"	INTEGER,
	"DEPTHTOROOTRESTRICTION"	INTEGER,
	"DEPTHTOWATERTABLE"	INTEGER,
	"DEPTHTOIMPASSABLECOARSEFRAGMENTS"	INTEGER,
	"PROBLEMATICSITE"	TEXT,
	"DEPTHTOSEEPAGE"	INTEGER,
	"SOIL_PIT_PHOTO"	TEXT,
	"PRI_ECO"	TEXT,
	"PRI_ECO_PCT"	INTEGER,
	"SEC_ECO"	TEXT,
	"SEC_ECO_PCT"	INTEGER,
	"AZIMUTH"	INTEGER,
	"DISTANCE"	INTEGER,
	"SOIL_PIT_PHOTO1"	BLOB,
	"SOIL_PIT_PHOTO2"	BLOB,
	"SUBSTRATENOTE"	TEXT,
	"POREPATTERNCODE"	INTEGER,
	"MINERALTEXTURECODE"	TEXT,
	"DECOMPOSITIONCODE"	TEXT,
	"PITAZIMUTH"	INTEGER,
	"PITDISTANCE"	NUMERIC,
	"SUBSTRATEDATE"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"MODEOFDEPOSITIONRANK1"	INTEGER,
	"MODEOFDEPOSITIONRANK2"	INTEGER,
	"SUBSTRATEPERSON"	TEXT,
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("ECOSITEID")
);

CREATE INDEX "ECOSITEDELETED" ON "ECOSITE" (
	"IsDeleted"
);

-- DWD definition

CREATE TABLE "DWD" (
	"DWDID"	TEXT,
	"PLOTID"	TEXT,
	"LINENUMBER"	INTEGER,
	"DWDNUM"	INTEGER,
	"SPECIESCODE"	INTEGER,
	"SMALLDIAMETER"	NUMERIC,
	"DECOMPOSITIONCLASS"	INTEGER,
	"DOWNWOODYDEBRISORIGINCODE"	TEXT,
	"TILTANGLE"	INTEGER,
	"DOWNWOODYDEBRISLENGTH"	NUMERIC,
	"MOSS"	TEXT,
	"BURNED"	TEXT,
	"HOLLOW"	TEXT,
	"IS_ACCUM"	TEXT,
	"ACCUMULATIONLENGTH"	NUMERIC,
	"ACCUMULATIONDEPTH"	NUMERIC,
	"PERCENTCONIFER"	INTEGER,
	"PERCENTHARDWOOD"	INTEGER,
	"LARGEDIAMETER"	NUMERIC,
	"DIAMETER"	NUMERIC,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"ERRORCOUNT"	INTEGER DEFAULT 0,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("DWDID")
);

CREATE INDEX "DWDLINENUM" ON "DWD" (
	"PLOTID",
	"LINENUMBER",
	"DWDNUM"
);
CREATE INDEX "DWDID" ON "DWD" (
	"DWDID"
);
CREATE INDEX "DWDDELETED" ON "DWD" (
	"IsDeleted"
);

-- DEFORMITY definition

CREATE TABLE "DEFORMITY" (
	"DEFORMITYID"	TEXT,
	"TREEID"	TEXT,
	"DEFORMITYTYPECODE"	INTEGER,
	"CAUSE"	INTEGER,
	"HEIGHTFROM"	NUMERIC,
	"HEIGHTTO"	NUMERIC,
	"QUADRANTCODE"	TEXT,
	"EXTENT"	INTEGER,
	"DEGREELEANARCH"	INTEGER,
	"AZIMUTH"	INTEGER,
	"DEFORMITYLENGTH"	NUMERIC,
	"DEFORMITYWIDTH"	NUMERIC,
	"SCUFF"	INTEGER,
	"SCRAPE"	INTEGER,
	"GOUGE"	INTEGER,
	"OLD_FEEDING_CAVITY"	TEXT,
	"NEW_FEEDING_CAVITY"	TEXT,
	"OLD_NEST_CAVITY"	TEXT,
	"NEW_NEST_CAVITY"	TEXT,
	"STICK_NEST"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("DEFORMITYID")
);

CREATE INDEX "DEFORMITYFROMTO" ON "DEFORMITY" (
	"TREEID",
	"HEIGHTFROM",
	"HEIGHTTO"
);
CREATE INDEX "DEFORMITYID" ON "DEFORMITY" (
	"DEFORMITYID"
);
CREATE INDEX "DEFORMITYDELETED" ON "DEFORMITY" (
	"IsDeleted"
);


-- PERSON definition

CREATE TABLE "PERSON" (
	"PERSONID"	TEXT,
	"PROJECTID"	TEXT,
	"FIRSTNAME"	TEXT,
	"LASTNAME"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("PERSONID")
);

CREATE INDEX "PERSONDELETED" ON "PERSON" (
	"IsDeleted"
);


-- PHOTO definition

CREATE TABLE "PHOTO" (
	"PLOTID"	TEXT,
	"PHOTOID"	TEXT,
	"PHOTOTYPE"	TEXT,
	"DESCRIPTION"	TEXT,
	"PHOTONUMBER"	INTEGER,
	"FRAMENUMBER"	INTEGER,
	"AZIMUTH"	INTEGER,
	"DISTANCE"	NUMERIC,
	"Created"	TEXT,
	"LastModified"	TEXT,
	"IsDeleted"	TEXT,
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("PHOTOID")
);

CREATE INDEX "PHOTOID" ON "PHOTO" (
	"PHOTOID"
);
CREATE INDEX "PHOTODELETED" ON "PHOTO" (
	"IsDeleted"
);


-- SMALLTREETALLY definition

CREATE TABLE "SMALLTREETALLY" (
	"SMALLTREETALLYID"	TEXT,
	"PLOTID"	TEXT,
	"SPECIESCODE"	INTEGER,
	"DBH"	NUMERIC,
	"HEIGHT"	NUMERIC,
	"COUNT"     INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("SMALLTREETALLYID")
);

-- VEGETATIONCENSUS definition

CREATE TABLE "VEGETATIONCENSUS" (
	"VEGETATIONCENSUSID"	TEXT,
	"PLOTID"	TEXT,
	"VSNSPECIESCODE"	TEXT,
	"SPECIMENNUMBER"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	"ERRORCOUNT"	INTEGER,
	"ERRORMSG"	TEXT,
	PRIMARY KEY("VEGETATIONCENSUSID")
);

CREATE INDEX "VEGETATTIONCENSUSID" ON "VEGETATIONCENSUS" (
	"VEGETATIONCENSUSID"
);
CREATE INDEX "VEGCENSUSDELETED" ON "VEGETATIONCENSUS" (
	"IsDeleted"
);


-- App-specific table
-- "USER" definition

CREATE TABLE "USER" (
	"USERID"	INTEGER,
	"USERNAME"	TEXT,
	"PWD"	TEXT,
	"POST"	TEXT,
	"PUT"	TEXT,
	"GET"	TEXT,
	"KEY"	TEXT,
	"CONNECTION"	TEXT,
	PRIMARY KEY("USERID" AUTOINCREMENT)
);






















-- Crosstabular Indexes

CREATE INDEX IF NOT EXISTS "VEGETATOINPLOT" ON "VEGETATION" (
	"PLOTID"
);
CREATE INDEX IF NOT EXISTS "TREEPLOT" ON "TREE" (
	"PLOTID"	ASC
);
CREATE INDEX IF NOT EXISTS "TREETREE" ON "TREE" (
	"TREEID"	ASC
);
CREATE INDEX IF NOT EXISTS "STEMMAPTREE" ON "STEMMAP" (
	"TREEID"	ASC
);
CREATE INDEX IF NOT EXISTS "SOILPLOT" ON "SOIL" (
	"PLOTID"
);
CREATE INDEX IF NOT EXISTS "SMALLTREEPLOT" ON "SMALLTREE" (
	"PLOTID"	ASC
);
CREATE INDEX IF NOT EXISTS "PLOTPROJECT" ON "PLOT" (
	"PROJECTID"	ASC
);
CREATE INDEX "PERSONPROJECT" ON "PERSON" (
	"PROJECTID",
	"LASTNAME"
);
CREATE INDEX IF NOT EXISTS "ECOSITEPLOT" ON "ECOSITE" (
	"PLOTID"	ASC
);
CREATE INDEX IF NOT EXISTS "DWDPLOT" ON "DWD" (
	"PLOTID"
);
CREATE INDEX IF NOT EXISTS "DEFORMITYPLOT" ON "DEFORMITY" (
	"TREEID"	ASC
);
CREATE INDEX  IF NOT EXISTS "VEGETATIONCENSUSPLOT" ON "VEGETATIONCENSUS" (
	"PLOTID"
);
CREATE INDEX  IF NOT EXISTS "PHOTOPLOT" ON "PHOTO" (
	"PLOTID"
);

COMMIT;
