BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "VEGETATION" (
	"VEGETATIONID"	TEXT,
	"PLOTID"	TEXT,
	"SPECIES"	TEXT,
	"QUAD1"	INTEGER,
	"QUAD2"	INTEGER,
	"QUAD3"	INTEGER,
	"QUAD4"	INTEGER,
	"ELCLAYER3"	INTEGER,
	"ELCLAYER4"	INTEGER,
	"ELCLAYER5"	INTEGER,
	"ELCLAYER6"	INTEGER,
	"ELCLAYER7"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("VEGETATIONID")
);
CREATE TABLE IF NOT EXISTS "TREE" (
	"TREEID"	TEXT,
	"PLOTID"	TEXT,
	"SECTION"	INTEGER,
	"TREENUM"	INTEGER,
	"SPECIES"	INTEGER,
	"TAG_TYPE"	TEXT,
	"ORIGIN"	TEXT,
	"STATUS"	TEXT,
	"VIGOUR"	INTEGER,
	"HT_TO_DBH"	NUMERIC,
	"DBH"	NUMERIC,
	"HT"	NUMERIC,
	"LENGTH"	NUMERIC,
	"DBH_IN"	TEXT,
	"CROWN_IN"	TEXT,
	"LIVE_CROWN_RATIO"	INTEGER,
	"CROWN_CLASS"	TEXT,
	"CROWN_POSITION"	INTEGER,
	"CROWN_DAMAGE"	INTEGER,
	"DEFOLIATING_INSECT"	INTEGER,
	"FOLIAR_DISEASE"	INTEGER,
	"STEM_QUALITY"	TEXT,
	"BARK_RETENTION"	INTEGER,
	"WOOD_CONDITION"	INTEGER,
	"DECAY_CLASS"	INTEGER,
	"MORT_CAUSE"	INTEGER,
	"BROKEN_TOP"	TEXT,
	"AGE"	INTEGER,
	"AGE_OFFICE"	INTEGER,
	"AGE_CORE_LENGTH"	NUMERIC,
	"AZIMUTH"	NUMERIC,
	"DISTANCE"	NUMERIC,
	"CROWN_WIDTH1"	NUMERIC,
	"CROWN_WIDTH2"	NUMERIC,
	"COMMENTS"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("TREEID")
);
CREATE TABLE IF NOT EXISTS "STEMMAP" (
	"STEMMAPID"	TEXT,
	"TREEID"	TEXT,
	"AZIMUTH"	INTEGER,
	"DISTANCE"	NUMERIC,
	"CROWN_AXIS_LONG"	NUMERIC,
	"CROWN_AXIS_SHORT"	NUMERIC,
	"OFFSET_AZIMUTH"	INTEGER,
	"OFFSET_DISTANCE"	NUMERIC,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("STEMMAPID")
);
CREATE TABLE IF NOT EXISTS "SOIL" (
	"SOILID"	TEXT,
	"PLOTID"	TEXT,
	"LAYER"	INTEGER,
	"FROM"	INTEGER,
	"TO"	INTEGER,
	"HORIZON"	TEXT,
	"VON_POST"	TEXT,
	"TEXTURE"	TEXT,
	"PORE_PATTERN"	TEXT,
	"STRUCTURE"	TEXT,
	"COLOUR"	TEXT,
	"MOTTLE_COLOUR"	TEXT,
	"PERCENT_GRAVEL"	INTEGER,
	"PERCENT_COBBLE"	INTEGER,
	"PERCENT_STONE"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("SOILID")
);
CREATE TABLE IF NOT EXISTS "SMALLTREE" (
	"SMALLTREEID"	TEXT,
	"PLOTID"	TEXT,
	"SPECIES"	INTEGER,
	"HT_CLASS1_COUNT"	INTEGER,
	"HT_CLASS2_COUNT"	INTEGER,
	"HT_CLASS3_COUNT"	INTEGER,
	"HT_CLASS4_COUNT"	INTEGER,
	"HT_CLASS5_COUNT"	INTEGER,
	"HT_CLASS6_COUNT"	INTEGER,
	"HT_CLASS7_COUNT"	INTEGER,
	"HT_CLASS8_COUNT"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("SMALLTREEID")
);
CREATE TABLE IF NOT EXISTS "PROJECT" (
	"PROJECTID"	TEXT,
	"NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	"PROJECT_DATE"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("PROJECTID")
);
CREATE TABLE IF NOT EXISTS "PLOT" (
	"PLOTID"	TEXT,
	"PROJECTID"	TEXT,
	"PLOT_TYPE"	TEXT,
	"PLOTNUM"	TEXT,
	"ADMINISTRATIVE"	INTEGER,
	"FOREST_DISTRICT"	TEXT,
	"FMU"	INTEGER,
	"MANAGEMENT_UNIT"	INTEGER,
	"IMAGE_ANNOTATION"	TEXT,
	"PLOTKEY"	TEXT,
	"PLOT_DATE"	TEXT,
	"MEASUREMENT_TYPE"	TEXT,
	"LEAD_SPP"	INTEGER,
	"ORIGIN"	INTEGER,
	"CANOPY_STRUCTURE"	TEXT,
	"MATURITY"	TEXT,
	"CROWN_CLOSURE"	INTEGER,
	"FIELD_CREW1"	TEXT,
	"FIELD_CREW2"	TEXT,
	"FIELD_CREW3"	TEXT,
	"DECLINATION"	TEXT,
	"UTM_ZONE"	INTEGER,
	"UTM_EASTING"	NUMERIC,
	"UTM_NORTHING"	NUMERIC,
	"DATUM"	TEXT,
	"COMMENTS"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("PLOTID")
);
CREATE TABLE IF NOT EXISTS "ECOSITE" (
	"ECOSITEID"	TEXT,
	"PLOTID"	TEXT,
	"HUMUS_FORM"	INTEGER,
	"DRAINAGE"	INTEGER,
	"STRATIFIED"	TEXT,
	"EFFECTIVE_PORE_PATTERN"	TEXT,
	"ELC_SUBSTRATE_TYPE"	TEXT,
	"DEPTH_TO_DISTINCT_MOTTLES"	INTEGER,
	"DEPTH_TO_PROMINENT_MOTTLES"	INTEGER,
	"DEPTH_TO_GLEY"	INTEGER,
	"DEPTH_TO_BEDROCK"	INTEGER,
	"DEPTH_TO_CARBONATES"	INTEGER,
	"MOISTURE_REGIME_DEPTH_CLASS"	TEXT,
	"MOISTURE_REGIME"	TEXT,
	"MODE_OF_DEPOSITION1"	TEXT,
	"MODE_OF_DEPOSITION2"	TEXT,
	"FUNCTIONAL_ROOTING_DEPTH"	INTEGER,
	"MAXIMUM_ROOTING_DEPTH"	INTEGER,
	"DEPTH_TO_ROOT_RESTRICTION"	INTEGER,
	"DEPTH_TO_WATER_TABLE"	INTEGER,
	"DEPTH_TO_COARSE_FRAGS"	INTEGER,
	"PROBLEMATIC_SITE_PROTOCOL_CLASS"	INTEGER,
	"SEEPAGE"	TEXT,
	"SOIL_PIT_PHOTO"	TEXT,
	"PRI_ECO"	TEXT,
	"PRI_ECO_PCT"	INTEGER,
	"SEC_ECO"	TEXT,
	"SEC_ECO_PCT"	INTEGER,
	"AZIMUTH"	INTEGER,
	"DISTANCE"	INTEGER,
	"SOIL_PIT_PHOTO1"	BLOB,
	"SOIL_PIT_PHOTO2"	BLOB,
	"COMMENTS"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("ECOSITEID")
);
CREATE TABLE IF NOT EXISTS "DWD" (
	"DWDID"	TEXT,
	"PLOTID"	TEXT,
	"LINE"	INTEGER,
	"DWDNUM"	INTEGER,
	"SPECIES"	INTEGER,
	"DIAM"	NUMERIC,
	"DECOMP_CLASS"	INTEGER,
	"ORIGIN"	TEXT,
	"TILT_ANGLE"	INTEGER,
	"LENGTH"	NUMERIC,
	"SMALL_DIAM"	NUMERIC,
	"LARGE_DIAM"	NUMERIC,
	"GT_50_MOSS"	TEXT,
	"BURNED"	TEXT,
	"HOLLOW"	TEXT,
	"IS_ACCUM"	TEXT,
	"ACCUM_LENGTH"	NUMERIC,
	"ACCUM_DEPTH"	NUMERIC,
	"PERCENT_CONIFER"	INTEGER,
	"PERCENT_DECID"	INTEGER,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("DWDID")
);
CREATE TABLE IF NOT EXISTS "DEFORMITY" (
	"DEFORMITYID"	TEXT,
	"TREEID"	TEXT,
	"TYPE"	INTEGER,
	"CAUSE"	INTEGER,
	"HT_FROM"	NUMERIC,
	"HT_TO"	NUMERIC,
	"QUAD"	TEXT,
	"EXTENT"	INTEGER,
	"LEAN"	INTEGER,
	"AZIMUTH"	INTEGER,
	"LENGTH"	NUMERIC,
	"WIDTH"	NUMERIC,
	"PCT_SCUFF"	INTEGER,
	"PCT_SCRAPE"	INTEGER,
	"PCT_GOUGE"	INTEGER,
	"OLD_FEEDING_CAVITY"	TEXT,
	"NEW_FEEDING_CAVITY"	TEXT,
	"OLD_NEST_CAVITY"	TEXT,
	"NEW_NEST_CAVITY"	TEXT,
	"STICK_NEST"	TEXT,
	"Created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastModified"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"IsDeleted"	TEXT DEFAULT 'N',
	PRIMARY KEY("DEFORMITYID")
);
CREATE INDEX IF NOT EXISTS "VEGETATOINPLOT" ON "VEGETATION" (
	"PLOTID"
);
CREATE INDEX IF NOT EXISTS "TREEPLOT" ON "TREE" (
	"PLOTID"	ASC
);
CREATE INDEX IF NOT EXISTS "TREETREE" ON "TREE" (
	"TREEID"	ASC
);
CREATE INDEX IF NOT EXISTS "STEMMAPTREE" ON "STEMMAP" (
	"TREEID"	ASC
);
CREATE INDEX IF NOT EXISTS "SOILPLOT" ON "SOIL" (
	"PLOTID"
);
CREATE INDEX IF NOT EXISTS "SMALLTREEPLOT" ON "SMALLTREE" (
	"PLOTID"	ASC
);
CREATE INDEX IF NOT EXISTS "PLOTPROJECT" ON "PLOT" (
	"PROJECTID"	ASC
);
CREATE INDEX IF NOT EXISTS "ECOSITEPLOT" ON "ECOSITE" (
	"PLOTID"	ASC
);
CREATE INDEX IF NOT EXISTS "DWDPLOT" ON "DWD" (
	"PLOTID"
);
CREATE INDEX IF NOT EXISTS "DEFORMITYPLOT" ON "DEFORMITY" (
	"TREEID"	ASC
);
COMMIT;
